### ISSUE TITLE
License change to BSD

### ISSUE THREAD

**Issue by sharoonthomas** [fulfilio/python-magento#7]
We have been receiving several requests from potential users and contributors if the library's license could be changed to a less restrictive license like BSD. Given the purpose of this python package is to be a library people could use to build their applications on, I agree with the idea. 

I had asked around once before when similar requests came up and most of the contributors had agreed.

Would like to use this ticket to track down permission to change the license to BSD.

**Comment by sharoonthomas** [comment]
@iiijjjii @aventurella @sethwoodworth @guewen @glyphobet @raimonesteve @tarunbhardwaj @www-xilus-es your thoughts?

**Comment by guewen** [comment]
I agree with the change.

**Comment by iiijjjii** [comment]
Yeah, I'm fine with it.

**Comment by tarunbhardwaj** [comment]
Yes this should be in BSD

**Comment by sethwoodworth** [comment]
Sorry, a voice of dissension.
I'm pro AGPL.  I prefer companies who wish to profit from a library, pay for the library, if they are unwilling to use the AGPL.  If a company is interested in using the AGPL and contributing source, then they may use the AGPL. ([Zed Shaw's argument](https://zedshaw.com/archive/why-i-algpl/) essentially).
Regardless, I don't consider my contributions to this repo copyrightable.
